### ISSUE TITLE
Use bitcore db service to store the opcode metadata

### ISSUE THREAD

**Issue by christopheradams** [poexio/specialops#11]
The package currently creates its own database.

**Comment by qinfengling** [comment]
It can store the metadata in main database now.
https://github.com/poexio/specialops/compare/master...enhancement/db

About changes:
1.  Change the [key, value] encoding from `UTF-8` to `HEX`, 
    The database open with the binary option. https://github.com/bitpay/bitcore-node/blob/master/lib/services/db/index.js#L81
2. Store the tip with the same format of bitcore-node. format: [key, height + hash]
3. Add Utils module as Hexadecimal, Decimal and Hash checker
4. Add Encoding module to process the data storage and data conversion

**Comment by qinfengling** [comment]
Merged
