### ISSUE TITLE
Some protocols returns no results

### ISSUE THREAD

**Issue by clemsos** [poexio/specialops#18]
I have tried a basic request script using first `/protocols` then used the returned value to fetch the identifier and parse URLs for `identifiers/:identifier`. 

Here is the result

<img width="579" alt="screen shot 2018-05-13 at 13 03 09" src="https://user-images.githubusercontent.com/743246/39967172-bf005eac-56ae-11e8-99fa-b68dfa20933f.png">

Does that mean there is no transactions recorded with POET protocol in the BTC blockchain?

**Comment by clemsos** [comment]
It may be specific to POET as using metadata returns no result neither

<img width="1170" alt="screen shot 2018-05-13 at 13 17 54" src="https://user-images.githubusercontent.com/743246/39967252-1d0a18ac-56b0-11e8-94ad-0c10c4a89ae3.png">

**Comment by christopheradams** [comment]
1. STAMPD## needs to be URL encoded as `STAMPD%23%23`. Let's add a note to https://github.com/poexio/specialops#identifiers that the identifier has to be URL encoded.

2. I don't know where the prefix for POET came from. I do not see it mentioned anywhere in that PDF. If we don't know what it is, let's drop it from the list of supported protocols.

**Comment by qinfengling** [comment]
About 2.
We only found that in the testnet, so there is not any data like this in the mainnet.
The metadata comes from http://testnet.coinsecrets.org,
We have the metadata table here:
https://github.com/poexio/specialops/wiki/OP_RETURN-metadata#table-of-op_return-metadata

**Comment by christopheradams** [comment]
> About 2.
> We only found that in the testnet

Ok we can keep it in our list of protocols then. But should we dynamically filter out protocols that have no results on the blockchain. Would that solve the UX issue for you @clemsos?

**Comment by qinfengling** [comment]
Add note for identifier:
https://github.com/poexio/specialops/commit/659e43e27004a336c9bedd1425265d1bf5a64bea
