### ISSUE TITLE
List all txs that match an opcode identifier prefix

### ISSUE THREAD

**Issue by christopheradams** [poexio/specialops#5]
Given an opcode identifier prefix like `"DOCPROOF"`, return a list of all matching transactions, e.g.:

```
GET /opcodes/identifiers/DOCPROOF
```

**Comment by qinfengling** [comment]
Add the new endpoint.

https://github.com/poexio/specialops/compare/master...feature/identifier-prefix

**Comment by christopheradams** [comment]
Looks good!

**Comment by qinfengling** [comment]
Merged
